sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - docker
before_script:
  - docker login -e $IMMO_DOCKER_EMAIL -u $IMMO_DOCKER_USER -p $IMMO_DOCKER_PASS
after_success:
  - DEBUG=* node build-images.js
